[phases.setup]
nixPkgs = [
  "expat",
  "zlib",
  "libxml2",
  "libsbml",
  "glpk",
  "freetype",
  "libpng",
  "fontconfig"
]


[phases.install]
cmds = ["pip install -r requirements.txt"]

[build]
workingDirectory = "Backend/src"

[start]
cmd = "bash -c 'uvicorn main:app --host 0.0.0.0 --port $PORT'"
