[phases.setup]
nixPkgs = ["expat"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[build]
workingDirectory = "Backend"

[start]
cmd = "bash -c 'uvicorn main:app --host 0.0.0.0 --port $PORT'"

