GROUPED_PATHWAYS = [
    {"name": "Glycolysis/Gluconeogenesis", "category": "Carbohydrate Metabolism"},
    {"name": "Citric Acid Cycle", "category": "Carbohydrate Metabolism"},
    {"name": "Pyruvate Metabolism", "category": "Carbohydrate Metabolism"},
    {"name": "Pentose Phosphate Pathway", "category": "Carbohydrate Metabolism"},
    {"name": "Glyoxylate Metabolism", "category": "Carbohydrate Metabolism"},
    {"name": "Anaplerotic Reactions", "category": "Carbohydrate Metabolism"},
    {"name": "Valine, Leucine, and Isoleucine Metabolism", "category": "Amino Acid Metabolism"},
    {"name": "Methionine Metabolism", "category": "Amino Acid Metabolism"},
    {"name": "Arginine and Proline Metabolism", "category": "Amino Acid Metabolism"},
    {"name": "Alanine and Aspartate Metabolism", "category": "Amino Acid Metabolism"},
    {"name": "Tyrosine, Tryptophan, and Phenylalanine Metabolism", "category": "Amino Acid Metabolism"},
    {"name": "Threonine and Lysine Metabolism", "category": "Amino Acid Metabolism"},
    {"name": "Histidine Metabolism", "category": "Amino Acid Metabolism"},
    {"name": "Glycine and Serine Metabolism", "category": "Amino Acid Metabolism"},
    {"name": "Cysteine Metabolism", "category": "Amino Acid Metabolism"},
    {"name": "Glutamate Metabolism", "category": "Amino Acid Metabolism"},
    {"name": "tRNA Charging", "category": "Amino Acid Metabolism"},
    {"name": "Glycerophospholipid Metabolism", "category": "Lipid Metabolism"},
    {"name": "Membrane Lipid Metabolism", "category": "Lipid Metabolism"},
    {"name": "Lipopolysaccharide Biosynthesis / Recycling", "category": "Lipid Metabolism"},
    {"name": "Cell Envelope Biosynthesis", "category": "Cell Structure Biosynthesis"},
    {"name": "Murein Recycling", "category": "Cell Structure Biosynthesis"},
    {"name": "Murein Biosynthesis", "category": "Cell Structure Biosynthesis"},
    {"name": "Cofactor and Prosthetic Group Biosynthesis", "category": "Cofactor Metabolism"},
    {"name": "Folate Metabolism", "category": "Cofactor Metabolism"},
    {"name": "Nucleotide Salvage Pathway", "category": "Nucleotide Metabolism"},
    {"name": "Purine and Pyrimidine Biosynthesis", "category": "Nucleotide Metabolism"},
    {"name": "Oxidative Phosphorylation", "category": "Energy Metabolism"},
    {"name": "Methylglyoxal Metabolism", "category": "Energy Metabolism"},
    {"name": "Nitrogen Metabolism", "category": "Energy Metabolism"},
    {"name": "Extracellular exchange", "category": "Transport"},
    {"name": "Transport, Inner Membrane", "category": "Transport"},
    {"name": "Transport, Outer Membrane Porin", "category": "Transport"},
    {"name": "Transport, Outer Membrane", "category": "Transport"},
    {"name": "Inorganic Ion Transport and Metabolism", "category": "Transport"},
    {"name": "Biomass and maintenance functions", "category": "Objective Function Related"},
    {"name": "Alternate Carbon Metabolism", "category": "Objective Function Related"},
    {"name": "Unassigned", "category": "Unassigned"},
]
